name: ribs_http
version: 1.0.0-dev.1
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  HTTP built on Ribs.

publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  meta:        ^1.9.1
  ribs_core:   ^1.0.0-dev.7
  ribs_effect: ^1.0.0-dev.1
  ribs_json:   ^1.0.0-dev.7

dev_dependencies:
  lint:       ^2.3.0
  ribs_check: ^1.0.0-dev.5
  test:       ^1.24.8
