name: ribs_http
version: 1.0.0-dev.1
homepage: https://cranst0n.github.io/ribs/
description: >
  HTTP built on Ribs.

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta:        ^1.9.1
  ribs_core:   ^1.0.0-dev.6
  ribs_json:   ^1.0.0-dev.6

dev_dependencies:
  daco:       ^0.2.6
  lint:       ^2.1.2
  ribs_check: ^1.0.0-dev.4
  test:       ^1.24.8
