version: 2
updates:

  # Github Actions dependencies updates config
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/bench"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/binary"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/check"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
      directory: "/packages/effect"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "chore"
        include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/ip"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/json"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/optics"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/units"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"