name: my_project

packages:
  - packages/**

scripts:

  test:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage"
    description: Run all dart tests in this project.
    packageFilters:
      dirExists: test

  coverage-report:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage" && find . -name coverage.lcov | xargs genhtml -o coverage-report
    description: Run all dart tests in this project and generate code coverage report.
    packageFilters:
      dirExists: test
