name: ribs

packages:
  - packages/**
  - website/snippets

scripts:

  test:
    run: melos exec -c 1 --fail-fast -- dart test
    description: Run all dart tests in this project.
    packageFilters:
      dirExists: test

  coverage:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage" && melos exec --dir-exists="test" format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib
    description: Run all dart tests in this project with code coverage data.
    packageFilters:
      dirExists: test
      ignore:
        - "snippets"

  coverage-report:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage" && melos exec --dir-exists="test" format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib && find . -name coverage.lcov | xargs genhtml -o coverage-report
    description: Run all dart tests in this project and generate code coverage report.
    packageFilters:
      dirExists: test
      ignore:
        - "snippets"

  doc:
    run: melos exec -c 12 --fail-fast -- dart doc
    description: Create API documentation for all packages.
    packageFilters:
      ignore: "snippets"

  analyze: melos exec -c1 -- dart analyze --fatal-infos .

  format: melos exec dart format --show=changed .

  outdated: melos exec dart pub outdated
  