name: my_project

packages:
  - packages/**

scripts:

  test:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage"
    description: Run all dart tests in this project.
    packageFilters:
      dirExists: test

  coverage-report:
    run: melos exec -c 1 --fail-fast -- dart test --coverage="coverage" && melos exec --dir-exists="test" format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib && find . -name coverage.lcov | xargs genhtml -o coverage-report
    description: Run all dart tests in this project and generate code coverage report.
    packageFilters:
      dirExists: test

  doc:
    run: melos exec -c 12 --fail-fast -- dart doc
    description: Create API documentation for all packages.
