name: ribs_parse
version: 1.0.0-dev.1
homepage: https://github.com/cranst0n/ribs
description: >
  Parsing library build on Ribs FP core.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta:       ^1.10.0
  ribs_core:  ^1.0.0-dev.5

dev_dependencies:
  daco:       ^0.2.6
  lint:       ^2.1.2
  path:       ^1.8.3
  ribs_check: ^1.0.0-dev.4
  test:       ^1.24.6
