name: ribs_fpdart_compat
version: 1.0.0-dev.1
homepage: https://github.com/cranst0n/ribs
description: >
  Ribs / fpdart compatibility layer.

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fpdart:      ^1.1.0
  ribs_core:   ^1.0.0-dev.4

dev_dependencies:
  lint:      ^2.1.2
  test:      ^1.24.6
