name: snippets
description: Dart snippets used in website.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  async: ^2.13.0
  postgres: ^3.5.0
  ribs_binary:
    path: ../../packages/binary/
  ribs_core:
    path: ../../packages/core/
  ribs_effect:
    path: ../../packages/effect/
  ribs_ip:
    path: ../../packages/ip/
  ribs_json:
    path: ../../packages/json/
  ribs_optics:
    path: ../../packages/optics/
  ribs_postgres:
    path: ../../packages/postgres/
  ribs_rill:
    path: ../../packages/rill/
  ribs_rill_io:
    path: ../../packages/rill_io/
  ribs_sql:
    path: ../../packages/sql/
  ribs_sqlite:
    path: ../../packages/sqlite/
  ribs_units:
    path: ../../packages/units/
  sqlite3: ^3.2.0
  sqlite3_connection_pool: ^0.2.0+1

dev_dependencies:
  lint:   ^2.8.0
  lints:  ^6.1.0
  ribs_check:
    path: ../../packages/check/
  test: ^1.0.0
