name: ribs_postgres
version: 1.0.0-dev.3
homepage: https://cranst0n.github.io/ribs/
repository: https://github.com/cranst0n/ribs
description: >
  PostgreSQL driver integration for ribs_sql, bringing functional IO-managed
  connections and streaming queries to Postgres.

topics:
  - postgres
  - database
  - sql
  - functional-programming

resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  postgres:    ^3.5.7
  ribs_core:   ^1.0.0-dev.16
  ribs_effect: ^1.0.0-dev.5
  ribs_rill:   ^1.0.0-dev.2
  ribs_sql:    ^1.0.0-dev.3

dev_dependencies:
  lint:       ^2.8.0
  lints:      ^6.1.0
  ribs_check: ^1.0.0-dev.10
  ribs_test:  ^1.0.0-dev.1
  test:       ^1.0.0
  testainers: ^0.3.0
