/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        { type: 'link', label: 'Core', href: 'https://pub.dev/documentation/ribs_core/latest/ribs_core/' },
        { type: 'link', label: 'Effect', href: 'https://pub.dev/documentation/ribs_effect/latest/ribs_effect/' },
        { type: 'link', label: 'Rill', href: 'https://pub.dev/documentation/ribs_rill/latest/ribs_rill/' },
        { type: 'link', label: 'JSON', href: 'https://pub.dev/documentation/ribs_json/latest/ribs_json/' },
        { type: 'link', label: 'Binary', href: 'https://pub.dev/documentation/ribs_binary/latest/ribs_binary/' },
        { type: 'link', label: 'Optics', href: 'https://pub.dev/documentation/ribs_optics/latest/ribs_optics/' },
        { type: 'link', label: 'Units', href: 'https://pub.dev/documentation/ribs_units/latest/ribs_units/' },
        { type: 'link', label: 'Check', href: 'https://pub.dev/documentation/ribs_check/latest/ribs_check/ribs_check-library.html' },
      ]
    },
  ],
};

export default sidebars;
