/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        { type: 'link', label: 'Core', href: 'https://pub.dev/documentation/ribs_core/latest/ribs_core/ribs_core-library.html' },
        { type: 'link', label: 'Effect', href: 'https://pub.dev/documentation/ribs_core/latest/ribs_effect/ribs_effect-library.html' },
        { type: 'link', label: 'JSON', href: 'https://pub.dev/documentation/ribs_json/latest/ribs_json/ribs_json-library.html' },
        { type: 'link', label: 'Binary', href: 'https://pub.dev/documentation/ribs_binary/latest/ribs_binary/ribs_binary-library.html' },
        { type: 'link', label: 'Optics', href: 'https://pub.dev/documentation/ribs_optics/latest/ribs_optics/ribs_optics-library.html' },
        { type: 'link', label: 'Units', href: 'https://pub.dev/documentation/ribs_untis/latest/ribs_untis/ribs_untis-library.html' },
        { type: 'link', label: 'Check', href: 'https://pub.dev/documentation/ribs_check/latest/ribs_check/ribs_check-library.html' },
      ]
    },
  ],
};

module.exports = sidebars;
